export const permissions = {
  campaign: {
    CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
    UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
    DELETE_CAMPAIGN: "DELETE_CAMPAIGN",
  },
  user: {
    CREATE_USER: "CREATE_USER",
    DELETE_USER: "DELETE_USER",
    UPDATE_USER: "UPDATE_USER",
  },
  category: {
    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
  },
};
